apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    app: result
spec:
  containers:
    - name: result
      image: dockersamples/examplevotingapp_result:before
      ports:
        - containerPort: 80